version: '3.8'

services:
  ffc-main:
    build:
      dockerfile: Dockerfile
    image: nestjs
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db:
